### ISSUE TITLE
It does not post :(

### ISSUE THREAD

**Issue by bluusun** [northernbeacheswebsites/wp-linkedin-auto-publish#1]
Installed, Authorized and it all looks good but my Linkedin page/account does not do any posts. Is there a log to debug?

**Comment by northernbeacheswebsites** [comment]
Hi,

Please create a support request on WordPress.org <http://wordpress.org/> thanks,


Martin Gibson
Northern Beaches Websites

Collaroy Plateau, NSW, Australia, 2097
mobile: 0400 491 712

**Comment by bluusun** [comment]
User error :) Works now.
